<a href="https://colab.research.google.com/github/noufalshehri/OCCUPATIONAL-BURNOUT-RATE-PREDICTION/blob/main/OBP_data_preprocessing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Data Pre-processing#

In [ ]:
#importing needed libraries
import pandas as pd
import scipy
import numpy as np
from sklearn.preprocessing import MinMaxScaler
import seaborn as sns
import matplotlib.pyplot as plt
from datetime import datetime

In [ ]:
# Load the dataset
df = pd.read_csv('OBP.csv')
print(df.head())

                Employee ID Date of Joining  Gender Company Type  \
0  fffe32003000360033003200      2008-09-30  Female      Service
1      fffe3700360033003500      2008-11-30    Male      Service
2  fffe31003300320037003900      2008-03-10  Female      Product
3  fffe32003400380032003900      2008-11-03    Male      Service
4  fffe31003900340031003600      2008-07-24  Female      Service

  WFH Setup Available  Designation  Resource Allocation  Mental Fatigue Score  \
0                  No          2.0                  3.0                   3.8
1                 Yes          1.0                  2.0                   5.0
2                 Yes          2.0                  NaN                   5.8
3                 Yes          1.0                  1.0                   2.6
4                  No          3.0                  7.0                   6.9

   Burn Rate
0       0.16
1       0.36
2       0.49
3       0.20
4       0.52

In [ ]:
# check the information of the dataset
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 22750 entries, 0 to 22749
Data columns (total 9 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Employee ID           22750 non-null  object
 1   Date of Joining       22750 non-null  object
 2   Gender                22750 non-null  object
 3   Company Type          22750 non-null  object
 4   WFH Setup Available   22750 non-null  object
 5   Designation           22750 non-null  float64
 6   Resource Allocation   21369 non-null  float64
 7   Mental Fatigue Score  20633 non-null  float64
 8   Burn Rate             21626 non-null  float64
dtypes: float64(4), object(5)
memory usage: 1.6+ MB

In [ ]:
# check the null values
df.isnull().sum()

Employee ID                0
Date of Joining            0
Gender                     0
Company Type               0
WFH Setup Available        0
Designation                0
Resource Allocation     1381
Mental Fatigue Score    2117
Burn Rate               1124
dtype: int64

In [ ]:
# drop rows that contains null values
df=df.dropna()
df.isnull().sum()

Employee ID             0
Date of Joining         0
Gender                  0
Company Type            0
WFH Setup Available     0
Designation             0
Resource Allocation     0
Mental Fatigue Score    0
Burn Rate               0
dtype: int64

In [ ]:
# find and numerize categorical features
df=df.replace('No','0')
df=df.replace('Yes','1')

df=df.replace('Male','0')
df=df.replace('Female','1')

# Import label encoder
from sklearn import preprocessing

# label_encoder object knows
# how to understand word labels.
label_encoder = preprocessing.LabelEncoder()

# Encode labels in column 'Company Type'.
df['Company Type']= label_encoder.fit_transform(df['Company Type'])

df['Company Type'].unique()
df

,Employee ID,Date of Joining,Gender,Company Type,WFH Setup Available,Designation,Resource Allocation,Mental Fatigue Score,Burn Rate
0,fffe32003000360033003200,2008-09-30,1,1,0,2.0,3.0,3.8,0.16
1,fffe3700360033003500,2008-11-30,0,1,1,1.0,2.0,5.0,0.36
3,fffe32003400380032003900,2008-11-03,0,1,1,1.0,1.0,2.6,0.20
4,fffe31003900340031003600,2008-07-24,1,1,0,3.0,7.0,6.9,0.52
5,fffe3300350037003500,2008-11-26,0,0,1,2.0,4.0,3.6,0.29
...,...,...,...,...,...,...,...,...,...
22743,fffe3300390030003600,2008-12-15,1,0,1,1.0,3.0,6.0,0.48
22744,fffe32003500370033003200,2008-05-27,0,0,0,3.0,7.0,6.2,0.54
22746,fffe33003000350031003800,2008-01-19,1,0,1,3.0,6.0,6.7,0.59
22748,fffe33003300320036003900,2008-01-10,1,1,0,2.0,5.0,5.9,0.52
22749,fffe3400350031003800,2008-01-06,0,0,0,3.0,6.0,7.8,0.61

In [ ]:
# drop Employee ID because it's not needed in the modelling
df=df.drop(columns =['Employee ID'])
df

,Date of Joining,Gender,Company Type,WFH Setup Available,Designation,Resource Allocation,Mental Fatigue Score,Burn Rate
0,2008-09-30,1,1,0,2.0,3.0,3.8,0.16
1,2008-11-30,0,1,1,1.0,2.0,5.0,0.36
3,2008-11-03,0,1,1,1.0,1.0,2.6,0.20
4,2008-07-24,1,1,0,3.0,7.0,6.9,0.52
5,2008-11-26,0,0,1,2.0,4.0,3.6,0.29
...,...,...,...,...,...,...,...,...
22743,2008-12-15,1,0,1,1.0,3.0,6.0,0.48
22744,2008-05-27,0,0,0,3.0,7.0,6.2,0.54
22746,2008-01-19,1,0,1,3.0,6.0,6.7,0.59
22748,2008-01-10,1,1,0,2.0,5.0,5.9,0.52
22749,2008-01-06,0,0,0,3.0,6.0,7.8,0.61

In [ ]:
now = datetime.now() # current date and time
date_time = now.strptime(date_time,"%Y-%m-%d")
print("date and time:",date_time)

date and time: 2023-11-28 00:00:00

In [ ]:
from datetime import datetime
df.dtypes

Date of Joining          object
Gender                   object
Company Type              int64
WFH Setup Available      object
Designation             float64
Resource Allocation     float64
Mental Fatigue Score    float64
Burn Rate               float64
dtype: object

In [ ]:
df["Date of Joining"] = abs((df["Date of Joining"]- date_time))

TypeError: ignored

In [ ]:
df.dtypes

In [ ]:
# take the year only out of the date in Date of Joining column
df["Date of Joining"]=df["Date of Joining"].astype(str)

In [ ]:
df

In [ ]:
df.dtypes

In [ ]:
# drop Employee ID because it's not needed in the modelling
df=df.drop(columns =['Employee ID'])
df

In [ ]:
# saving the dataframe
df.to_csv('OBP_preprocessed.csv')